

package training;

import java.util.*;
import java.io.Serializable;
import de.hybris.platform.util.*;
import de.hybris.platform.core.*;
import de.hybris.platform.jalo.JaloBusinessException;
import de.hybris.platform.jalo.type.*;
import de.hybris.platform.persistence.type.*;
import de.hybris.platform.persistence.enumeration.*;
import de.hybris.platform.persistence.property.PersistenceManager;
import de.hybris.platform.persistence.*;

/**
 * Generated by hybris Platform.
 */
@SuppressWarnings({"cast","unused","boxing","null", "PMD"})
public class GeneratedTypeInitializer extends AbstractTypeInitializer
{
	/**
	 * Generated by hybris Platform.
	 */
	public GeneratedTypeInitializer( ManagerEJB manager, Map params )
	{
		super( manager, params );
	}


	/**
	 * Generated by hybris Platform.
	 */
	@Override
	protected void performRemoveObjects( ManagerEJB manager, Map params ) throws JaloBusinessException
	{
		// no-op by now
	}

	/**
	 * Generated by hybris Platform.
	 */
	@Override
	protected final void performCreateTypes( final ManagerEJB manager, Map params ) throws JaloBusinessException
	{
		// performCreateTypes
	
	
		createItemType(
			"MyAddress",
			"GenericItem",
			org.training.jalo.MyAddress.class,
			"de.hybris.platform.persistence.training_MyAddress",
			false,
			null,
			false
		);
	
		createItemType(
			"MyShippingAddress",
			"MyAddress",
			org.training.jalo.MyShippingAddress.class,
			"de.hybris.platform.persistence.training_MyShippingAddress",
			false,
			null,
			false
		);
	
		createItemType(
			"MyBillingAddress",
			"MyAddress",
			org.training.jalo.MyBillingAddress.class,
			"de.hybris.platform.persistence.training_MyBillingAddress",
			false,
			null,
			false
		);
	
		createEnumerationType(
			"Sex",
			de.hybris.platform.jalo.enumeration.EnumerationValue.class
				
		);
	
		createCollectionType(
			"AddressCollCollection",
			"MyAddress",
			CollectionType.COLLECTION
		);
	
		createCollectionType(
			"AddressListCollection",
			"MyAddress",
			CollectionType.LIST
		);
	
		createCollectionType(
			"AddressSetCollection",
			"MyAddress",
			CollectionType.SET
		);
	
	}

	/**
	 * Generated by hybris Platform.
	 */
	@Override
	protected final void performModifyTypes( final ManagerEJB manager, Map params ) throws JaloBusinessException
	{
		// performModifyTypes
	

	
	
				single_createattr_MyAddress_name();
			
				single_createattr_MyAddress_line1();
			
				single_createattr_MyAddress_city();
			
				single_createattr_MyAddress_county();
			
				single_createattr_MyAddress_country();
			
				single_createattr_MyAddress_postcode();
			

	}

	
	public void single_createattr_MyAddress_name() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"MyAddress", 
					"name",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_MyAddress_line1() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"MyAddress", 
					"line1",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_MyAddress_city() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"MyAddress", 
					"city",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_MyAddress_county() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"MyAddress", 
					"county",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_MyAddress_country() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"MyAddress", 
					"country",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_MyAddress_postcode() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"MyAddress", 
					"postcode",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	


	/**
	 * Generated by hybris Platform.
	 */
	@Override
	protected final void performCreateObjects( final ManagerEJB manager, Map params ) throws JaloBusinessException
	{
		// performCreateObjects
	
	
		createEnumerationValues(
			"Sex",
			false,
			Arrays.asList( new String[] {
			
				"Select",
				"Male",
				"Female",
				"Other"
			} )
		);
	
				{
				Map customPropsMap = new HashMap();
				
					customPropsMap.put( "catalogItemType", java.lang.Boolean.TRUE );
				
					customPropsMap.put( "catalogVersionAttributeQualifier", "catalogVersion" );
				
					customPropsMap.put( "uniquekeyAttributeQualifier", "code" );
				
				setItemTypeProperties(
					"MyAddress",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_MyAddress_name();
		
			single_setAttributeProperties_MyAddress_line1();
		
			single_setAttributeProperties_MyAddress_city();
		
			single_setAttributeProperties_MyAddress_county();
		
			single_setAttributeProperties_MyAddress_country();
		
			single_setAttributeProperties_MyAddress_postcode();
		
				{
				Map customPropsMap = new HashMap();
				
					customPropsMap.put( "catalogItemType", java.lang.Boolean.TRUE );
				
					customPropsMap.put( "catalogVersionAttributeQualifier", "catalogVersion" );
				
					customPropsMap.put( "uniquekeyAttributeQualifier", "code" );
				
				setItemTypeProperties(
					"MyShippingAddress",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
				{
				Map customPropsMap = new HashMap();
				
					customPropsMap.put( "catalogItemType", java.lang.Boolean.TRUE );
				
					customPropsMap.put( "catalogVersionAttributeQualifier", "catalogVersion" );
				
					customPropsMap.put( "uniquekeyAttributeQualifier", "code" );
				
				setItemTypeProperties(
					"MyBillingAddress",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
				setDefaultProperties(
					"AddressCollCollection",
					true,
					true,
					null
				);
			
				setDefaultProperties(
					"AddressListCollection",
					true,
					true,
					null
				);
			
				setDefaultProperties(
					"AddressSetCollection",
					true,
					true,
					null
				);
			
				setDefaultProperties(
					"Sex",
					true,
					true,
					null
				);
			
	}


		
						public void single_setAttributeProperties_MyAddress_name() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"MyAddress", 
								"name",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_MyAddress_line1() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"MyAddress", 
								"line1",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_MyAddress_city() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"MyAddress", 
								"city",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_MyAddress_county() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"MyAddress", 
								"county",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_MyAddress_country() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"MyAddress", 
								"country",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_MyAddress_postcode() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"MyAddress", 
								"postcode",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
}

	